config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  root :to => 'credit_cards#index'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  after_validation :find_type
  after_validation :luhn

#Methods for luhn validation

#First checking the type of card

	private

	def find_type
		# Making sure that the card number is passed as a string
		credit_card = self.number.delete(' ')
		# Set of statements to return the appropriate card type
		# Firstly the code checks the cards's length
		# Secondly regexp, returns 0 which signals validation
		self.provider = "Unknown"
		self.provider = "AMEX"	if credit_card.length == 15 && (credit_card =~ /^(34|37)/) == 0
		self.provider = "Discover"	if credit_card.length == 16 && (credit_card =~ /^6011/) == 0
		self.provider = "MasterCard"	if credit_card.length == 16 && (credit_card =~ /^(5[1-5])/) == 0
		self.provider = "VISA"	if [13,16].include?(credit_card.length) && (credit_card =~ /^4/) == 0
	end

#Secondly applying the Luhn algorithm on the number to check is the number valid or not

	def luhn
    result = 0
    nums = self.number.delete(' ').split("").reverse!
    nums.each_with_index do |item, index|
      if index.odd?
      	if item.to_i*2>9
      		result+= item.to_i*2-9
        else 
        	result+= item.to_i*2
        end
      else
        result +=item.to_i
    	end
  	end
  	if (result % 10) == 0
      self.validation = "valid"
  	else
      self.validation = "invalid"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  def index
    @credit_cards = CreditCard.all
  end

  def show
  end

  def new
    @credit_card = CreditCard.new
  end

  def edit
  end

  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :index, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :provider, :validation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/index.html.erb
<h1>List of the cards</h1>

<table>
  <thead>
    <tr>
      <h2><th>Provider</th></h2>
      <h2><th>Number</th></h2>
      <h2><th>Validation</th></h2>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><p><%= credit_card.provider %>:</p></td>
        <td><p><%= credit_card.number %></p></td>
        <td><p>(<%= credit_card.validation %>)</p></td>
        <td><p><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </p></tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'New Credit card', new_credit_card_path %><td>

app/views/credit_cards/new.html.erb
<h1>Add a new credit card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @credit_card.provider %>
</p>

<p>
  <strong>Validation:</strong>
  <%= @credit_card.validation %>
</p>


<%= link_to 'Back', credit_cards_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The link to <a href="https://github.com/ponyczek/mwr_beta">GitHub Repository</a>
    Created by <a href="http://www.theavalanche.eu/">Adrian Grzywaczewski</a>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luhn Card Validator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>